//
//  SplashProtocols.swift
//  PaymentDemo
//
//  Created linhvt on 4/19/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import Foundation

// MARK: - Builder
protocol SplashBuilderProtocol: class {

}

// MARK: - Presenter
protocol SplashPresenterProtocol: class {
    
    func viewDidLoad()
    
}

// MARK: - View
protocol SplashViewProtocol: class, ShowMessageProtocol {
    var presenter: SplashPresenterProtocol? { get }
    
    func dismiss()
}

