//
//  SplashModule.swift
//  PaymentDemo
//
//  Created linhvt on 4/19/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class SplashModule: SplashBuilderProtocol {

    static func build() -> UIViewController {
        let view = SplashViewController(nibName: "SplashViewController", bundle: nil)
        let presenter = SplashPresenter(view: view)
        
        view.presenter = presenter
        
        return view
    }
    
    
    static func show(onViewController viewController: UIViewController) {
        let vc = SplashModule.build()
        vc.modalPresentationStyle = .fullScreen
        viewController.present(vc, animated: true, completion: nil)
    }
    
}
