//
//  SplashPresenter.swift
//  PaymentDemo
//
//  Created linhvt on 4/19/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import Foundation
import MinervaUI

class SplashPresenter: SplashPresenterProtocol {

    weak private var view: SplashViewProtocol?
    var dismissHandler: (() -> Void)?
    
    init(view: SplashViewProtocol, dismissHandler: @escaping () -> Void) {
        self.view = view
        self.dismissHandler = dismissHandler
    }
    
    func viewDidLoad() {
        TerraInstanceCenter.shared.loadTerra { [weak self] (isSuccess) in
            guard isSuccess else {
                self?.view?.showMessage("Terra load failed!")
                return
            }
            DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
                self?.view?.dismiss()
                self?.dismissHandler?()
            }
        }
    }
}
