//
//  SplashPresenter.swift
//  PaymentDemo
//
//  Created linhvt on 4/19/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import Foundation
import MinervaUI

class SplashPresenter: SplashPresenterProtocol {

    weak private var view: SplashViewProtocol?

    init(view: SplashViewProtocol) {
        self.view = view
    }
    
    func viewDidLoad() {
        TerraInstanceCenter.shared.loadTerra { [weak self] (isSuccess) in
            guard isSuccess else {
                self?.view?.showMessage("Terra load failed!")
                return
            }
//            TerraPaymentUI.configureWith(app: terraApp)
            self?.view?.dismiss()
        }
    }
}
